[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contract/=lib/chainlink-brownie-contracts/contracts/"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
